### ISSUE TITLE
Check Kinto for keyboard mapping

### ISSUE THREAD

**Issue by probonopd** [probonopd/hello#8]
https://medium.com/@benreaves/kinto-a-mac-inspired-keyboard-mapping-for-linux-58f731817c0

https://github.com/rbreaves/kinto/

> If there’s anything missing that breaks the illusion for you then please let me know and I will do what I can to resolve it. The only goal I have with Kinto is to make something that will allow anyone to flow between any Linux desktop and a Mac desktop without any real differences, as far as the keyboard is concerned.

**Comment by probonopd** [comment]
Also check `ctrl:swap_lalt_lctl	Swap Left Alt key with Left Ctrl key`

https://github.com/probonopd/LIVEstep/issues/14

**Comment by probonopd** [comment]
https://github.com/rbreaves/kinto

Consider keysnail for key bindings that are welcoming to Mac switchers.

Key dependency:
https://github.com/mooz/xkeysnail

Apparently never been tested on FreeBSD.

```
sudo pip-3.7 install keysnail
ERROR: Could not find a version that satisfies the requirement keysnail (from versions: none)                                                               
ERROR: No matching distribution found for keysnail
```

cc @rbreaves

**Comment by probonopd** [comment]
This works:

```
cd /tmp
git clone --depth 1 https://github.com/mooz/xkeysnail.git\ncd xkeysnail\n

sudo pip-3.7 install --upgrade .
Processing /tmp/xkeysnail
Requirement already satisfied, skipping upgrade: evdev in /usr/local/lib/python3.7/site-packages (from xkeysnail==0.4.0) (0.8.1)
Requirement already satisfied, skipping upgrade: python-xlib in /usr/local/lib/python3.7/site-packages (from xkeysnail==0.4.0) (0.27)
Collecting inotify_simple
  Downloading inotify_simple-1.3.5.tar.gz (9.7 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/local/lib/python3.7/site-packages (from python-xlib->xkeysnail==0.4.0) (1.14.0)
Using legacy 'setup.py install' for xkeysnail, since package 'wheel' is not installed.
Using legacy 'setup.py install' for inotify-simple, since package 'wheel' is not installed.
Installing collected packages: inotify-simple, appdirs, xkeysnail
    Running setup.py install for inotify-simple ... done
    Running setup.py install for xkeysnail ... done
Successfully installed appdirs-1.4.4 inotify-simple-1.3.5 xkeysnail-0.4.0
```

**Comment by probonopd** [comment]
But it looks like Kinto needs some tweaking for FreeBSD:

```
./setup.py 
awk: can't open file /etc/os-release
 source line number 1
/bin/sh: ./system-config/dename.sh: not found

Kinto 1.2-4 build 98d5309
Type in Linux like it's a Mac.

Traceback (most recent call last):
  File "./setup.py", line 137, in <module>
    subprocess.check_call(shlex.split("./xkeysnail_service.sh"))
  File "/usr/local/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './xkeysnail_service.sh': './xkeysnail_service.sh'
```

**Comment by probonopd** [comment]
@rbreaves if you like I can give you ssh access to a FreeBSD/helloSystem machine.

**Comment by rbreaves** [comment]
> @rbreaves if you like I can give you ssh access to a FreeBSD/helloSystem machine.

That would work, if you want to DM me on Twitter or message me via any other secure way feel free. I’ll try & touch on it sometime tomorrow.

**Comment by probonopd** [comment]
Please ping me once you have time, because the machine doesn't have a fixed IP
